using System.Reflection;
using ArgoBooks.Core.Enums;
using ArgoBooks.Core.Models.Entities;
using ArgoBooks.Core.Models.Inventory;
using ArgoBooks.ViewModels;
using Xunit;

namespace ArgoBooks.Tests.ViewModels;

/// <summary>
/// Drives the real StockAdjustmentsModalsViewModel add/undo/redo flow: an adjustment moves the item's
/// InStock and writes a StockAdjustment ledger row, and undo/redo restore both exactly.
/// </summary>
public class StockAdjustmentsModalsViewModelTests : ModalViewModelTestBase
{
    private StockAdjustmentsModalsViewModel NewVmWithItem(int startStock)
    {
        Company.Products.Add(new Product { Id = "P1", Name = "Widget" });
        Company.Inventory.Add(new InventoryItem { Id = "I1", ProductId = "P1", InStock = startStock });
        var vm = new StockAdjustmentsModalsViewModel();
        vm.OpenAddModal();
        vm.SelectedInventoryOption = vm.AvailableInventoryItems.First();
        return vm;
    }

    [Fact]
    public void AddAdjustment_ChangesStockAndWritesLedgerRow()
    {
        var vm = NewVmWithItem(100);
        vm.AdjustmentType = "Add";
        vm.AdjustmentQuantity = "50";

        vm.SaveAdjustmentCommand.Execute(null);

        Assert.Equal(150, Company.Inventory.Single().InStock);
        var adj = Assert.Single(Company.StockAdjustments);
        Assert.Equal(100, adj.PreviousStock);
        Assert.Equal(150, adj.NewStock);
    }

    [Fact]
    public void AddAdjustment_UndoThenRedo_RestoresStockAndLedger()
    {
        var vm = NewVmWithItem(100);
        vm.AdjustmentType = "Add";
        vm.AdjustmentQuantity = "50";
        vm.SaveAdjustmentCommand.Execute(null);

        Undo();
        Assert.Equal(100, Company.Inventory.Single().InStock);
        Assert.Empty(Company.StockAdjustments);

        Redo();
        Assert.Equal(150, Company.Inventory.Single().InStock);
        Assert.Single(Company.StockAdjustments);
    }

    [Fact]
    public void RemoveMoreThanInStock_IsRejected()
    {
        var vm = NewVmWithItem(10);
        vm.AdjustmentType = "Remove";
        vm.AdjustmentQuantity = "25"; // more than the 10 in stock

        vm.SaveAdjustmentCommand.Execute(null);

        // No change and no ledger row; the guard blocks negative stock.
        Assert.Equal(10, Company.Inventory.Single().InStock);
        Assert.Empty(Company.StockAdjustments);
    }

    private static readonly PropertyInfo ConfirmationDialogProperty =
        typeof(App).GetProperty(nameof(App.ConfirmationDialog))!;

    /// <summary>
    /// Seeds a manual "Add 10" that later sales took the stock down from, leaving
    /// <paramref name="inStock"/>, and returns that Add.
    /// </summary>
    private StockAdjustment SeedAddOf10(int inStock)
    {
        Company.Products.Add(new Product { Id = "P1", Name = "Widget" });
        Company.Inventory.Add(new InventoryItem { Id = "I1", ProductId = "P1", InStock = inStock });
        var added = new StockAdjustment
        {
            Id = "ADJ-00001", InventoryItemId = "I1", AdjustmentType = AdjustmentType.Add,
            Quantity = 10, PreviousStock = 0, NewStock = 10
        };
        Company.StockAdjustments.Add(added);
        if (inStock < 10)
        {
            Company.StockAdjustments.Add(new StockAdjustment
            {
                Id = "ADJ-00002", InventoryItemId = "I1", AdjustmentType = AdjustmentType.Remove,
                Quantity = 10 - inStock, PreviousStock = 10, NewStock = inStock, IsAutoGenerated = true
            });
        }
        return added;
    }

    /// <summary>Deletes the adjustment from the page, confirming if the app asks.</summary>
    private static void DeleteConfirmed(StockAdjustment adjustment)
    {
        var dialog = new ConfirmationDialogViewModel();
        var priorDialog = ConfirmationDialogProperty.GetValue(null);
        var priorContext = SynchronizationContext.Current;
        // With no context, the delete's await resumes inline as soon as the dialog is answered.
        SynchronizationContext.SetSynchronizationContext(null);
        ConfirmationDialogProperty.SetValue(null, dialog);
        try
        {
            new StockAdjustmentsModalsViewModel().OpenDeleteConfirm(new StockAdjustmentDisplayItem
            {
                Id = adjustment.Id, ProductName = "Widget",
                AdjustmentType = adjustment.AdjustmentType, Quantity = adjustment.Quantity
            });
            if (dialog.IsOpen)
                dialog.PrimaryActionCommand.Execute(null);
        }
        finally
        {
            ConfirmationDialogProperty.SetValue(null, priorDialog);
            SynchronizationContext.SetSynchronizationContext(priorContext);
        }
    }

    // Adding an adjustment refuses to leave stock below zero, so deleting one must too: 8 of the 10
    // added were sold, and taking all 10 back out would leave -8.
    [Fact]
    public void DeleteAdd_ThatWouldLeaveStockBelowZero_IsRefused()
    {
        var added = SeedAddOf10(inStock: 2);

        DeleteConfirmed(added);

        Assert.Equal(2, Company.Inventory.Single().InStock);
        Assert.Contains(added, Company.StockAdjustments);
    }

    [Fact]
    public void DeleteAdd_ThatLeavesStockAtZero_Goes()
    {
        var added = SeedAddOf10(inStock: 10);

        DeleteConfirmed(added);

        Assert.Equal(0, Company.Inventory.Single().InStock);
        Assert.DoesNotContain(added, Company.StockAdjustments);
    }
}
