namespace ArgoBooks.Core.Models.Insights;

/// <summary>
/// Represents the complete insights data generated by the analytics engine.
/// </summary>
public class InsightsData
{
    /// <summary>
    /// Summary statistics for the insights.
    /// </summary>
    public InsightsSummary Summary { get; set; } = new();

    /// <summary>
    /// Forecasted growth metrics.
    /// </summary>
    public ForecastData Forecast { get; set; } = new();

    /// <summary>
    /// Revenue trend insights.
    /// </summary>
    public List<InsightItem> RevenueTrends { get; set; } = [];

    /// <summary>
    /// Detected anomalies.
    /// </summary>
    public List<InsightItem> Anomalies { get; set; } = [];

    /// <summary>
    /// Forecast-related insights.
    /// </summary>
    public List<InsightItem> Forecasts { get; set; } = [];

    /// <summary>
    /// Business recommendations.
    /// </summary>
    public List<InsightItem> Recommendations { get; set; } = [];

    /// <summary>
    /// When the insights were generated.
    /// </summary>
    public DateTime GeneratedAt { get; set; } = DateTime.Now;

    /// <summary>
    /// Whether there is sufficient data to generate meaningful insights.
    /// </summary>
    public bool HasSufficientData { get; set; }

    /// <summary>
    /// Message explaining data insufficiency (if applicable).
    /// </summary>
    public string? InsufficientDataMessage { get; set; }
}

/// <summary>
/// Summary statistics for the insights page.
/// </summary>
public class InsightsSummary
{
    /// <summary>
    /// Total number of insights generated.
    /// </summary>
    public int TotalInsights { get; set; }

    /// <summary>
    /// Number of trends detected.
    /// </summary>
    public int TrendsDetected { get; set; }

    /// <summary>
    /// Number of anomalies detected.
    /// </summary>
    public int AnomaliesDetected { get; set; }

    /// <summary>
    /// Number of opportunities/recommendations.
    /// </summary>
    public int Opportunities { get; set; }

    /// <summary>
    /// Number of months of historical data available.
    /// </summary>
    public int MonthsOfData { get; set; }
}

/// <summary>
/// Forecasted growth data.
/// </summary>
public class ForecastData
{
    /// <summary>
    /// Number of months the forecast period covers (e.g., 0.99 for 30 days, 2.96 for 90 days).
    /// </summary>
    public decimal PeriodMonths { get; set; } = 1;

    /// <summary>
    /// Forecasted revenue for the next period.
    /// </summary>
    public decimal ForecastedRevenue { get; set; }

    /// <summary>
    /// Revenue growth percentage.
    /// </summary>
    public decimal RevenueGrowthPercent { get; set; }

    /// <summary>
    /// Forecasted expenses for the next period.
    /// </summary>
    public decimal ForecastedExpenses { get; set; }

    /// <summary>
    /// Expense growth percentage (positive means expenses increased).
    /// </summary>
    public decimal ExpenseGrowthPercent { get; set; }

    /// <summary>
    /// Forecasted profit for the next period.
    /// </summary>
    public decimal ForecastedProfit { get; set; }

    /// <summary>
    /// Profit growth percentage.
    /// </summary>
    public decimal ProfitGrowthPercent { get; set; }

    /// <summary>
    /// Expected number of new customers.
    /// </summary>
    public int ExpectedNewCustomers { get; set; }

    /// <summary>
    /// Customer growth percentage.
    /// </summary>
    public decimal CustomerGrowthPercent { get; set; }

    /// <summary>
    /// Confidence score for the predictions (0-100).
    /// </summary>
    public double ConfidenceScore { get; set; }

    /// <summary>
    /// Confidence level description (Low, Medium, High).
    /// </summary>
    public string ConfidenceLevel { get; set; } = "Medium";

    /// <summary>
    /// Number of months of data used for forecasting.
    /// </summary>
    public int DataMonthsUsed { get; set; }
}

/// <summary>
/// Represents a single insight item.
/// </summary>
public class InsightItem
{
    /// <summary>
    /// Title of the insight.
    /// </summary>
    public string Title { get; set; } = string.Empty;

    /// <summary>
    /// Detailed description of the insight.
    /// </summary>
    public string Description { get; set; } = string.Empty;

    /// <summary>
    /// Optional recommendation for action.
    /// </summary>
    public string? Recommendation { get; set; }

    /// <summary>
    /// Severity/importance level (Info, Warning, Success, Critical).
    /// </summary>
    public InsightSeverity Severity { get; set; } = InsightSeverity.Info;

    /// <summary>
    /// Category of the insight.
    /// </summary>
    public InsightCategory Category { get; set; }

    /// <summary>
    /// The metric value associated with this insight.
    /// </summary>
    public decimal? MetricValue { get; set; }

    /// <summary>
    /// The percentage change associated with this insight.
    /// </summary>
    public decimal? PercentageChange { get; set; }

    /// <summary>
    /// Whether this insight has an actionable recommendation.
    /// </summary>
    public bool HasRecommendation => !string.IsNullOrEmpty(Recommendation);
}

/// <summary>
/// Severity levels for insights.
/// </summary>
public enum InsightSeverity
{
    /// <summary>Informational insight (blue).</summary>
    Info,

    /// <summary>Positive insight (green).</summary>
    Success,

    /// <summary>Warning that needs attention (orange/yellow).</summary>
    Warning,

    /// <summary>Critical issue requiring immediate action (red).</summary>
    Critical
}

/// <summary>
/// Categories for insights.
/// </summary>
public enum InsightCategory
{
    /// <summary>Revenue-related trends.</summary>
    RevenueTrend,

    /// <summary>Expense-related trends.</summary>
    ExpenseTrend,

    /// <summary>Anomaly detection.</summary>
    Anomaly,

    /// <summary>Forecasting insights.</summary>
    Forecast,

    /// <summary>Business recommendations.</summary>
    Recommendation,

    /// <summary>Customer-related insights.</summary>
    Customer,

    /// <summary>Product-related insights.</summary>
    Product,

    /// <summary>Invoice/payment insights.</summary>
    Payment,

    /// <summary>Inventory-related insights.</summary>
    Inventory
}

/// <summary>
/// Date range for analysis.
/// </summary>
public class AnalysisDateRange
{
    /// <summary>
    /// Start date of the analysis period.
    /// </summary>
    public DateTime StartDate { get; set; }

    /// <summary>
    /// End date of the analysis period.
    /// </summary>
    public DateTime EndDate { get; set; }

    /// <summary>
    /// Name of the date preset (if applicable).
    /// </summary>
    public string? PresetName { get; set; }

    /// <summary>
    /// Creates a date range from preset name.
    /// </summary>
    public static AnalysisDateRange FromPreset(string presetName)
    {
        var now = DateTime.Now;
        var range = new AnalysisDateRange { PresetName = presetName };

        switch (presetName)
        {
            case "This Month":
                range.StartDate = new DateTime(now.Year, now.Month, 1);
                range.EndDate = now;
                break;

            case "Last Month":
                var lastMonth = now.AddMonths(-1);
                range.StartDate = new DateTime(lastMonth.Year, lastMonth.Month, 1);
                range.EndDate = new DateTime(lastMonth.Year, lastMonth.Month, DateTime.DaysInMonth(lastMonth.Year, lastMonth.Month));
                break;

            case "This Quarter":
                var quarterStart = new DateTime(now.Year, ((now.Month - 1) / 3) * 3 + 1, 1);
                range.StartDate = quarterStart;
                range.EndDate = now;
                break;

            case "Last Quarter":
                var lastQuarterEnd = new DateTime(now.Year, ((now.Month - 1) / 3) * 3 + 1, 1).AddDays(-1);
                var lastQuarterStart = lastQuarterEnd.AddMonths(-2);
                range.StartDate = new DateTime(lastQuarterStart.Year, lastQuarterStart.Month, 1);
                range.EndDate = lastQuarterEnd;
                break;

            case "This Year":
                range.StartDate = new DateTime(now.Year, 1, 1);
                range.EndDate = now;
                break;

            case "Last Year":
                range.StartDate = new DateTime(now.Year - 1, 1, 1);
                range.EndDate = new DateTime(now.Year - 1, 12, 31);
                break;

            case "All Time":
            default:
                range.StartDate = new DateTime(2000, 1, 1);
                range.EndDate = now;
                break;
        }

        return range;
    }

    /// <summary>
    /// Creates a custom date range.
    /// </summary>
    public static AnalysisDateRange Custom(DateTime start, DateTime end)
    {
        return new AnalysisDateRange
        {
            StartDate = start,
            EndDate = end,
            PresetName = "Custom Range"
        };
    }

    /// <summary>
    /// Gets the number of days in this range.
    /// </summary>
    public int DayCount => (EndDate - StartDate).Days + 1;

    /// <summary>
    /// Gets the previous period of the same length for comparison.
    /// </summary>
    public AnalysisDateRange GetPreviousPeriod()
    {
        var days = DayCount;
        return new AnalysisDateRange
        {
            StartDate = StartDate.AddDays(-days),
            EndDate = StartDate.AddDays(-1),
            PresetName = "Previous Period"
        };
    }
}
